music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [

    path('about/', views.About, name='about'),

    # /music/
    path('', views.IndexView.as_view(), name='index'),

    # /music/<album_id>
    path('album/<pk>', views.DetailView.as_view(), name='detail'),

    # /music/album/add
    path('album/add/', views.AlbumCreate.as_view(), name='album-add'),

    # /music/delete
    path('album/<pk>/delete/', views.AlbumDelete.as_view(), name='album-delete'),

    # /music/album/update
    path('album/<pk>/update/', views.AlbumUpdate.as_view(), name='album-update'),

    path('song/create/', views.SongCreate.as_view(), name='song-create'),
    path('song/all/', views.SongList.as_view(), name='song-list'),
    path('song/<id>/', views.SongDetail, name='song-detail'),

]

from django.conf import settings
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music.urls'), name='music'),
]

music/models.py
from django.db import models
from django.urls import reverse


class Album(models.Model):
    artist      = models.CharField(max_length=150)
    album_title = models.CharField(max_length=100)
    genre       = models.CharField(max_length=100)
    logo        = models.ImageField(upload_to="images/", blank=True, null=True)

    def get_absolute_url(self):
        return reverse(viewname='music:detail', kwargs={'pk': self.pk})
        
    def update_absolute_url(self):
        return reverse(viewname='music:album-update', kwargs={'pk': self.pk})

    def delete_absolute_url(self):
        return reverse(viewname='music:album-delete', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + " by " + self.artist


class Song(models.Model):
    album       = models.ForeignKey(Album, on_delete=models.CASCADE)
    files       = models.FileField(upload_to='musics/', null=True)
    song_title  = models.CharField(max_length=200)

    def __str__(self):
        return str(self.files) + ' - ' + str(self.id)

    def delete_song_absolute_url(self):
        return reverse(viewname='music:song-detail', kwargs={'id': self.id})

music/forms.py
from django import forms
from .models import Song


class SongCreateForm(forms.Form):
    album      = Forms.CharField() 
    song_title = Forms.CharField() 

    class Meta:
        model = Song

        fields = ['album', 'files', 'song_title']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Album, Song
from django.shortcuts import render, redirect, get_object_or_404


def About(request):
    return render(request, 'music/about.html', {})


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')
    template_name = 'music/album_confirm_delete.html'


class SongCreate(CreateView):
    model = Song
    fields = ['album', 'files', 'song_title']
    success_url = reverse_lazy('music:index')
    template_name = 'music/song_create.html'


class SongList(generic.ListView):
    template_name = 'music/song_list.html'
    context_object_name = 'all_songs'

    def get_queryset(self):
        return Song.objects.all()


class SongDelete(DeleteView):
    model = Song
    #success_url = reverse_lazy('music:song-list')
    template_name = 'music/song_delete.html'

    def get_queryset(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Song, id=id_)


def SongDetail(request, id):
    songs = get_object_or_404(Song, id=id)

    if request.method == "POST":
        songs.delete()
        return redirect('/')

    template_name = 'music/song_detail.html'
    context = {"all_songs": songs}

    return render(request, template_name, context)

music/templates/music/about.html
{% extends 'music/base.html' %}
{% block body %}

    <audio controls>
        <source src="../../../media/musics/08_Never_Too_Late.mp3" type="audio/mpeg">
    </audio>
{% endblock %}

music/templates/music/album_confirm_delete.html
{% extends 'music/base.html' %}
{% block body %}
    <form action="." method="post">{% csrf_token %}
        <p style="color: white;">Are you sure you want to delete the Album?</p>
        <input class="btn btn-danger" type="submit" value="Confirm" />
    </form>
{% endblock %}

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a new album{% endblock %}
{% block album_active %}active{% endblock %}

{% block body %}
<br/>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-7">
      <div class="card">
        <div class="card-body">

          <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'music/form-template.html' %}
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-outline-success">Submit</button>
              </div>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Mohsen{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png/" href="{% static 'favicon.ico' %}"/>

    <!-- golden link -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <!-- Font -->
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script|Great+Vibes|Pacifico|Satisfy" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">

</head>
<body>
    <!-- Bringing In Navbar -->
    {% include "music/navbar.html" %}

    <!-- Data Coming Through -->
    {% block body %}{% endblock %}

    <script src="{% static 'music/js/main.js' %}"></script>

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<br/>
<div class="container-fluid songs-container">

    <div class="row">
        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="card bg-secondary mb-3">
                <div class="card-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.logo %}
                            <img class="card-img-top" src="{{ album.logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <div class="card-title">
                        <h1>{{ album.album_title|title }}
                        <small>{{ album.genre|title }}</small></h1>
                    </div>
                    <h3>{{ album.artist }}</h3>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <div class="row">
                <ul class="nav nav-pills" style="margin-left: 15px; margin-bottom: 10px;">
                    <a href="{% url 'music:song-create' %}">
                        <button class="btn btn-outline-warning">
                            Add New Song
                        </button>
                    </a>
                </ul>
                
                <ul class="nav nav-pills" style="margin-left: 15px; margin-bottom: 10px;">
                    <a href="{{ album.update_absolute_url }}">
                        <button class="btn btn-outline-info">
                            Edit The Album
                        </button>
                    </a>
                </ul>

                <ul class="nav nav-pills" style="margin-left: 15px; margin-bottom: 10px;">
                    <a href="{{ album.delete_absolute_url }}">
                        <button class="btn btn-outline-danger">
                            Delete The Album
                        </button>
                    </a>
                </ul>
            </div>            

            <div class="card bg-secondary mb-3">
                <div class="card-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Audio File</th>
                                <th>Favorite</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in album.song_set.all %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>
                                        <audio controls style="margin:0px">
                                            <source src="{{ song.files.url }}" type="audio/mpeg">
                                        </audio>
                                    </td>

                                    <td>
                                        <a href="#" class="btn-favorite"><span class="fa fa-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                    <td>
                                        <a href="{{ song.delete_song_absolute_url }}">
                                            <button type="submit" class="btn btn-outline-danger btn-xs">
                                                <span class="fa fa-remove"></span>&nbsp; Delete
                                            </button>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
  <div class="form-group">
     <div class="col-sm-offset-2 col-sm-10">
       <span class="text-danger small">{{ field.errors }}</span>
     </div>
     <label class="control-label col-sm-2">{{ field.label_tag }}</label>
     <div class="col-sm-10">{{ field }}</div>
  </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}

    <br/>
    {% if all_albums %}
        <div class="container-fluid padding">
            <div class="row" style="margin-left: 10px">
                {% for album in all_albums %}
                    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-3">
                        <div class="card bg-secondary mb-3" style="width: 18rem; margin-bottom: 20px">
                            
                            {% if album.logo %}
                                <a href="{% url 'music:detail' album.id %}">
                                    <img src="{{ album.logo.url }}" class="card-img-top" style="width: 18rem">
                                </a>
                            {% endif %}
                            
                            <div class="card-body">
                                <h5 class="card-title">{{ album.album_title }}</h5>
                                <p class="card-text">By {{ album.artist }}</p>
                                <a href="{% url 'music:detail' album.id %}" class="btn btn-outline-warning btn-sm" role="button">View Details</a>
                            </div>
                            <!-- <a href="#">
                                <button type="button" class="btn btn-success">
                                    <span class="fa fa-plus"></span>&nbsp; Add an Album
                                </button>
                            </a> -->
                            
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <div class="col-sm-12">
            <br>
            <a href="#">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                </button>
            </a>
        </div>
    {% endif %}

{% endblock %}

music/templates/music/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <a class="navbar-brand" href="{% url 'music:index' %}">Mohsen Music</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item">
                <a class="nav-link" href="{% url 'music:index' %}">
                    <span class="fa fa-home" aria-hidden="true"></span>&nbsp; Home
                </a>
            </li>

            <li>
                <a class="nav-link" href="{% url 'music:index' %}">
                    <span class="fa fa-compact-disc" aria-hidden="true"></span>&nbsp; Albums
                </a>
            </li>
            
            <li>
                <a class="nav-link" href=" {% url 'music:song-list' %}">
                    <span class="fa fa-music" aria-hidden="true"></span>&nbsp; Songs
                </a>
            </li>
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
                    <span class="fas fa-crown" aria-hidden="true"></span>&nbsp; My websites
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="https://persiaempire.herokuapp.com/">Persian Empire</a>
                    <a class="dropdown-item" href="https://mohsenweb.herokuapp.com/">Mohsen Web</a>
                </div>
            </li>

            <li>
                <a class="nav-link" href="{% url 'music:about' %}">
                    <span class="fa fa-cd" aria-hidden="true"></span>&nbsp; About
                </a>
            </li>

        </ul>

        <ul class="navbar-nav">

            <li class="nav-item">
                <a class="nav-link" href="{% url 'music:album-add' %}">
                    <span class="fa fa-plus" aria-hidden="true"></span>&nbsp; Add Album
                </a>
            </li>

        </ul>

        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

<script src="https://kit.fontawesome.com/5f5fa5bcd8.js"></script>

music/templates/music/song_create.html
{% extends 'music/base.html' %}
{% block title %}Add a new album{% endblock %}
{% block album_active %}active{% endblock %}

{% block body %}
<br/>
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="card">
                <div class="card-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-outline-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/song_detail.html
{% extends 'music/base.html' %}

{% block body %}

    <br/>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <h5>Are you sure you want to delete the following song ?</h5>
                        </div>
                        <hr/>

                        <audio controls>
                            <source src="{{ all_songs.files.url }}" type="audio/mpeg">
                        </audio>

                        <div class="footer">
                            <form action="." method="post">{% csrf_token %}
                                <br />
                                <input class="btn btn-danger" type="submit" value="Yes, I do." />
                                <input class="btn btn-info" type="submit" value="No, I don't." />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

music/templates/music/song_list.html
{% extends 'music/base.html' %}

{% block body %}
    <br/>
        <div class="row" style="margin-left: 10px; margin-right: 10px">
            {% for song in all_songs %}
                <div class="col-sm-6">
                    <br />
                    <div class="card bg-secondary mb-3">
                        <div class="card-body">
                            <h4>{{ song.album }}</h3>
                            <h6>{{ song.song_title }}</h5>
                            <audio controls>
                                <source src="{{ song.files.url }}" type="audio/mpeg">
                            </audio>
                            <div class="footer">
                                <a href="{{ song.delete_song_absolute_url }}">
                                    <button class="btn btn-outline-danger">
                                        Delete The Song
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

{% endblock %}